### ISSUE TITLE
writeValueAsBytes failed if using LinkedHashMap

### ISSUE THREAD

**Issue by chaopeng** [FasterXML/jackson-dataformat-protobuf#10] opened 2015-05-31 04:49 UTC
```java
// write
ObjectMapper mapper = new ProtobufMapper();

NativeProtobufSchema fileSchema = ProtobufSchemaLoader.std.loadNative(new File("D:\\workspace\\bitcoinminer\\settings\\proto\\addressbook.proto")); // using protobuf's testcase

ProtobufSchema schema = fileSchema.forType("Person");

final ObjectWriter w = mapper.writer(schema);

Map person = new LinkedHashMap<>(); // it is ok if using HashMap. 

Map phone1 = new HashMap<>();
phone1.put("type", 1);
phone1.put("number", "123456");

Map phone2 = new HashMap<>();
phone2.put("type", 0);
phone2.put("number", "654321");

List<Map> phones = new ArrayList<>();
phones.add(phone1);
phones.add(phone2);

person.put("name", "aaaa");
person.put("id", 1111);
person.put("phone", phones);

// I have try this...
// Map m = new HashMap<>();
// m.putAll(person);
// byte[] bytes = w.writeValueAsBytes(person);

byte[] bytes = w.writeValueAsBytes(person);

// read
ObjectReader r =  mapper.readerFor(HashMap.class).with(schema);
Object person2 = r.readValue(bytes); // person2 will just has phone field
```

Why I try to use LinkedHashMap, because I try to use jackson-dataformat-protobuf in groovy like this: 

```groovy
def person = [name: "aaaa", id: 123, email: "111@111.com",
        phone: [
            [type:0, number:"111111"],
            [number: "222222"]
    ]
];

def bytes = w.writeValueAsBytes(person);
```

**Comment by cowtowncoder** [comment] 2015-06-01 17:07
The problem may be that there is no native `Map` type in protoc. One can emulate Maps using key/value Records that repeat, but the question there is how to map that to look like generic key/value pairs to Jackson.

Could you cut'n paste `protoc` definition here (file `D:\\workspace\\bitcoinminer\\settings\\proto\\addressbook.proto`)? I'll see how type is defined, and whether it'd be possible to support that.
I assume this could be a common use case, and would like to support it if at all possible.

**Comment by chaopeng** [comment] 2015-06-01 17:12
package tutorial;

message Person {
  required string name = 1;
  required int32 id = 2;        // Unique ID number for this person.
  optional string email = 3;

  enum PhoneType {
    MOBILE = 0;
    HOME = 1;
    WORK = 2;
  }

  message PhoneNumber {
    required string number = 1;
    optional PhoneType type = 2 [default = HOME];
  }

  repeated PhoneNumber phone = 4;
}

// Our address book file is just one of these.
message AddressBook {
  repeated Person person = 1;
}

**Comment by cowtowncoder** [comment] 2015-06-01 21:02
Thanks! Yes, I see, I think that ought to work, although I need to check it bit further.

**Comment by cowtowncoder** [comment] 2015-06-03 02:42
Interesting. Yes, I can reproduce the problem; only `phone` field is received, `name` and `id` missing for some reason.

**Comment by cowtowncoder** [comment] 2015-06-03 06:51
Found the root cause; was not flushing all content that was written. Fixed in master, will be in 2.6.0-rc2.

**Closed** 2015-06-03 06:50 UTC

**Comment by chaopeng** [comment] 2015-06-03 14:24
hi @cowtowncoder when will 2.6.0 rc2 release?

**Comment by cowtowncoder** [comment] 2015-06-03 19:08
@chaopeng Hopefully soon, within a week -- I hope to fix couple of bugs in `jackson-databind` before releasing it.

**Comment by chaopeng** [comment] 2015-06-03 19:11
Thank you.
